name: mdcii
on:
  push:
    branches:
      - main

jobs:
  build-push-anck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - run: make
